function dd_eqns = normaldyn_fun(in1,F,in3)
%NORMALDYN_FUN
%    DD_EQNS = NORMALDYN_FUN(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Nov-2020 17:00:54

Ip = in3(:,4);
dpsi = in1(:,4);
dx = in1(:,2);
f = in3(:,7);
g = in3(:,6);
l = in3(:,1);
mc = in3(:,3);
mp = in3(:,2);
psi = in1(:,3);
t2 = cos(psi);
t3 = sin(psi);
t4 = Ip.*mc;
t5 = Ip.*mp;
t6 = dpsi.^2;
t7 = l.^2;
t8 = mp.^2;
t9 = t2.^2;
t10 = mc.*mp.*t7;
t11 = t7.*t8;
t12 = t9.*t11;
t13 = -t12;
t14 = t4+t5+t10+t11+t13;
t15 = 1.0./t14;
dd_eqns = [-t15.*(-F.*Ip+Ip.*dx.*f-F.*mp.*t7+dx.*f.*mp.*t7-g.*t2.*t3.*t11+l.*t3.*t5.*t6+l.^3.*t3.*t6.*t8);l.*mp.*t15.*(F.*t2-dx.*f.*t2+g.*mc.*t3+g.*mp.*t3-l.*mp.*t2.*t3.*t6)];
